// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWJnI7ZlYA-GXXWXskTuKrLhiMLJhKLkM',
    appId: '1:59638025491:web:e5101ef8d4e043537c1ee6',
    messagingSenderId: '59638025491',
    projectId: 'sarvesh-weather',
    authDomain: 'sarvesh-weather.firebaseapp.com',
    storageBucket: 'sarvesh-weather.appspot.com',
    measurementId: 'G-5GW5GVEPFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG2Xq0hKS9OWL9LqXkoUUkDo5AyiI-Uc8',
    appId: '1:59638025491:android:be3c5e80213b80e67c1ee6',
    messagingSenderId: '59638025491',
    projectId: 'sarvesh-weather',
    storageBucket: 'sarvesh-weather.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaGaeWmWqB98iLPuCDn3o7YecuLJZILGw',
    appId: '1:59638025491:ios:bc1a240d35d244cb7c1ee6',
    messagingSenderId: '59638025491',
    projectId: 'sarvesh-weather',
    storageBucket: 'sarvesh-weather.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
